# Doggo Brain Check

In [1]:
#Import packages here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#URL to csvs
breed_info_url="https://raw.githubusercontent.com/OtterBots/DoggieData/main/AKC_Breed_Info.csv"
intel_url = "https://raw.githubusercontent.com/OtterBots/DoggieData/main/dog_intelligence.csv"

In [3]:
#Import data
df1 = pd.read_csv(breed_info_url)
df2 = pd.read_csv(intel_url)

### Join dataframes and process strings to numbers

In [4]:
#merge
dd=pd.merge(df1,df2, on='Breed')

#drop old index
dd.drop('index_x', axis=1,inplace=True)
dd.drop('index_y', axis=1,inplace=True)

#fill nan for dummies
dd['obey'].fillna('0%', inplace=True)

#convert obey to int
def obeyToInt(x):
    str(x)
    return int(x.replace('%',''))
dd['obey'] = dd['obey'].apply(obeyToInt)

#convert dimension collumns to float. Replace na with 0
def dimension(x):
    str(x)
    if x == 'na':
        return 0
    else:
        return float(x)

dd['height_low_inches'] = dd['height_low_inches'].apply(dimension)
dd['height_high_inches'] = dd['height_high_inches'].apply(dimension)
dd['weight_low_lbs'] = dd['weight_low_lbs'].apply(dimension)
dd['weight_high_lbs'] = dd['weight_high_lbs'].apply(dimension)

In [5]:
dd

,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,Classification,obey,reps_lower,reps_upper
0,Akita,26.0,28.0,80.0,120.0,Average Working/Obedience Intelligence,50,26,40
1,Bernese Mountain Dog,23.0,27.0,85.0,110.0,Excellent Working Dogs,85,5,15
2,Bloodhound,24.0,26.0,80.0,120.0,Lowest Degree of Working/Obedience Intelligence,0,81,100
3,Borzoi,26.0,28.0,70.0,100.0,Lowest Degree of Working/Obedience Intelligence,0,81,100
4,Bullmastiff,25.0,27.0,100.0,130.0,Fair Working/Obedience Intelligence,30,41,80
...,...,...,...,...,...,...,...,...,...
100,Japanese Chin,8.0,11.0,4.0,11.0,Fair Working/Obedience Intelligence,30,41,80
101,Maltese,8.0,10.0,4.0,6.0,Fair Working/Obedience Intelligence,30,41,80
102,Papillon,8.0,11.0,5.0,10.0,Brightest Dogs,95,1,4
103,Pomeranian,12.0,12.0,3.0,7.0,Excellent Working Dogs,85,5,15
104,Yorkshire Terrier,8.0,8.0,3.0,7.0,Above Average Working Dogs,70,16,25